---
title: "Assignment 3"
output: 
  pdf_document: default
  html_document: default 
  df_print: paged
lang: no-NB 
---

bibliography: references.bib

```{r}
library(tidyverse)
library(readr)
library(gapminder)
```

# 1 
The file ddf_concepts.cvs contains descriptions of a set of different variables including unemployment rate, adults with hiv, labour force participation, aid, causes of deaths, cell phones, cars, health factors, countries GDP etc. Each of the 600 variables further includes data. 

# 2

The file ddf--entities--geo--country.csv contains information of all the countries in the world where each country is categorized based on g77 and OECD, UN members/recognition, income groups, religion, latitude, longitude and region (Europe and world).

# 3

df--entities--geo--un_sdg_region.csv contains information about UN recognized regions. 

# 4
The gapminder dataset consist of 1704 rows and includes the following variables:

- Country 
- Continent 
- Year
- LifeExp
- Pop
- gdpPercap

Australia and New Zealand is assigned to Asia.

# 5 



